server:
  port: 8081

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gmall?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/xzw/gmall/user/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

